---
name: cs100-S2020-lab4
break: true
indent: 4
---

# Learn more about GatorGrader and its supported checks by visiting this web site:
# https://github.com/GatorEducator/gatorgrader

# Explanation:
# --> a check without an "--exact" runs a count for an entity as an "at least"
# --> checks below a file in a specified directory are for that specific file and directory
# --> checks that appear stand-alone are for an entire Git repository

# --> check the source code for various characteristics
src/main:
    java:
        labfour/ConvertGraphicImage.java:
            ConfirmFileExists
            CountSingleLineComments --language Java --count 6
            CountMultipleLineComments --language Java --count 5 --exact
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
            MatchFileFragment --fragment "package labfour;" --count 1 --exact
            MatchFileFragment --fragment "import java.io.File;" --count 1 --exact
            MatchFileFragment --fragment "import java.util.Date;" --count 1 --exact
            MatchFileFragment --fragment "import java.io.IOException;" --count 1 --exact
            MatchFileFragment --fragment "public static void convertImageToGreyScale(" --count 1 --exact
            MatchFileFragment --fragment "public static void convertImageToBrighten(" --count 1 --exact
            MatchFileFragment --fragment "public static void convertImageToDarken(" --count 1 --exact
            MatchFileFragment --fragment "new Date()" --count 1 --exact
            MatchFileFragment --fragment "println(" --count 10 --exact

# --> check the technical writing for various characteristics
writing/reflection.md:
    ConfirmFileExists
    CountFileWords --count 500
    CountMarkdownTags --tag "heading" --count 10 --exact
    CountMarkdownTags --tag "code" --count 5
    CountMarkdownTags --tag "code_block" --count 2 --exact
    CountMarkdownTags --tag "list" --count 1 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact

# --> check that the number of commits in the Git repository is beyond a threshold
CountCommits --count 5

# --> check that the program executes correctly and produces exactly the specified lines of output
ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle -q --console plain run"
CountCommandOutput --command "gradle -q --console plain run" --count 10 --exact

# --> check that the program produces the output sentences in this order:
#
# Gregory M. Kapfhammer Tue Oct 01 11:58:04 EDT 2019
# Starting to convert to grey-scale ...
#  Saved images/source_converted_greyscale.png
# ... Finished converting to grey-scale!
# Starting to convert to brighter, saturated image ...
#  Saved images/source_converted_brighten.png
# ... Finished converting to brighter, saturated image!
# Starting to convert to darker, subdued image ...
#  Saved images/source_converted_darken.png
# ... Finished converting to darker, subdued image!
#
# Note: checks for the specific numerical values that are fully determined by correct code
MatchCommandFragment --command "gradle -q --console plain run" --count 1 --fragment "source_converted_greyscale" --exact
MatchCommandFragment --command "gradle -q --console plain run" --count 1 --fragment "source_converted_brighten" --exact
MatchCommandFragment --command "gradle -q --console plain run" --count 1 --fragment "source_converted_darken" --exact
